### ISSUE TITLE
Iphone 6 Error

### ISSUE THREAD

**Issue by meska** [tito/pymoodstocks#2]
Hello, 
thank you for this useful plugin, I've been able to compile and use it on ipad mini but when I try on iphone 6 ( both with iOS 8.2) i get this error in xcode capturing a qrcode:

`
2015-03-26 18:26:47.546 mes[6859:3191848] Start the scanner
 Exception AttributeError: "'NoneType' object has no attribute 'type'" in 'pyobjus.pyobjus.protocol_method_implementation' ignored
`

**Comment by tito** [comment]
Hi. I did few fixes on kivy-ios/pyobjus for ARM64. Would you be able to recompile the toolchain with latest version (ensure your cache is deleted) and retry for you?

Thanks a lot :)

**Comment by meska** [comment]
Finally I had time to recompile with the latest Xcode ( 7.2 ) and toolchain and it's working great, thank you !
